#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/question_bank
#    username: root
#    password: 1234
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#  show-sql: true

#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: system
#    password: 1234
#
#jpa:
#        hibernate:
#          ddl-auto: update
#show-sql: true

server:
  servlet:
    # CORS 이슈때문에 일단 풀어놔야함.. 근데 보안상 이슈가 없는지는 모르겠음...
    cookie:
      same-site: None
      secure: true